language: python
python:
  - 3.7
cache:
  - pip
#  - directories:
#      - "$HOME/.pyenv"
# Would be great to cache Postgres here but dir names with spaces are split into two and escaping doesn't work
#      - "/c/Program\ Files/PostgreSQL"

env:
  - EXE_NAME=cjdb DISTPATH=$TRAVIS_BUILD_DIR/dist
os:
  - linux

branches:
  only:
    - master
    - develop
    # Run on release-* branches. Case insensitive.
    - /^(?i:release)-.*$/
    # A build is triggered with a tag push, in which case the branch name is
    # the tag name. Thus in order for on.tags:true to work, the tag-branch
    # must be safelisted
    - /^v.*$/

stages:
  - name: test
  - name: deploy
    # The executable is built only with python3.7 on the master branch
    if: branch = master AND env(TRAVIS_PYTHON_VERSION) = 3.7

jobs:
  include:
    - name: Python 3.7.5 on Bionic Ubuntu
      dist: bionic
      before_install:
        - export EXE_PKG="$EXE_NAME"_"$TRAVIS_CPU_ARCH"_ubuntu1804
    - name: Python 3.7.6 with pyenv on Windows
      os: windows
      language: shell
      before_install:
        - export PATH="$HOME/.pyenv/pyenv-win/bin:$HOME/.pyenv/pyenv-win/shims:$HOME/.pyenv/pyenv-win/versions/3.7.6-amd64:$HOME/.pyenv/pyenv-win/versions/3.7.6-amd64/Scripts:$PATH"
        - export EXE_PKG="$EXE_NAME"_"$TRAVIS_CPU_ARCH"_win10
        - if [ -z "$(ls -A $HOME/.pyenv)" ]; then
          git clone https://github.com/pyenv-win/pyenv-win.git $HOME/.pyenv;
          pyenv install -q 3.6.9-amd64;
          pyenv install -q 3.7.6-amd64;
          pyenv install -q 3.8.1-amd64;
          fi
        - pyenv rehash
        - pyenv global 3.7.6-amd64
        - pyenv local 3.7.6-amd64
        - python --version
        - python -m pip install --upgrade pip
        - pip install pywin32
        - choco install postgresql11

install:
  - pip install -U tox-travis
script:
  - tox

before_deploy:
  - pip install pyinstaller
  - pip install -r requirements.txt
  - pyinstaller --name $EXE_NAME --onefile cjio_dbexport/cli.py --distpath $DISTPATH
  - sleep 1
  - cat $TRAVIS_BUILD_DIR/build/cjdb/warn-cjdb.txt
  - ls -l $DISTPATH
  - $DISTPATH/$EXE_NAME || $DISTPATH/$EXE_NAME.exe
  - |
    case $TRAVIS_OS_NAME in
      windows)
        7z a -t7z $EXE_PKG.zip $DISTPATH/$EXE_NAME.exe
        rm $DISTPATH/$EXE_NAME.exe
        ;;
      linux)
        zip -rj $EXE_PKG.zip $DISTPATH/$EXE_NAME
        rm $DISTPATH/$EXE_NAME
        ;;
    esac

deploy:
  provider: releases
  cleanup: false
  token:
    secure: opgpAT2e9UvvFc629R5kdZZEeateOc0NaZgg/bcanVeYOAxxL1jUpkl6izFCUrweA4a/Ot+b1LaBchrQ5vW7DdhzSV/lGqEhPbrWLaJxgpoD23+MwIrT90eLSimz1xcyGe+5f6xXfJqE4vMIYRjQFJMM77R1ACPfX4RBwGJzdUdKz1ZKZ5g/HPJd6bPYIrbczbE4VKGw9i2k2hG3SWrjzs/88llUYM9hgNVloZreyFM1xS3k/A6OettPFmzpYm6ziFAm+v7ua7BfDj9X5pZSXmnGbFPMwW9eFBAENADg4GMZVkdqK2152Z6/+zlTWGwlhauzD/SsTBq/504vh1fsbKeb2fendabYEbXE8UQjywwg1q7rje5YK0RiBgKJ2Mpt0JKsk1zpJ5O4ajsgO2YdVnRhEb0Zu8An5pKvuvJrHX4vtf15jWCWRHy9uZaUx+C819KqXj8sd08jkNdAUtcw1eMTfldVeyiFbAx/I03SK8LQ9PUbvc2vlO/st8m0Qq81vg3Hgl8uGp7BUfWGUUXt1VSNC8ieijnBX60BC4nGtRZ+lCjazPjIuDv3mfRjG5g+wWwPdCznV3QPaiG17y/yJNdYbEVNd3SjkRWQipGgXsplF7UHBrRJLLR0JA/qWxayNpdTbINcTl/SeypqdEXylYNDsvy8Qts3k5vIUuSMBIg=
  file_glob: true
  # Travis cannot expand paths from env. variables under Windows here
  # (linux yes). So eg. $TRAVIS_BUILD_DIR/cjdb_*.zip leads to 'file not
  # found' on Windows
  file: cjdb_*.zip
  on:
    repo: cityjson/cjio_dbexport
    tags: true
  edge: true

notifications:
  email: false
